POST http://localhost:3333/videos
Content-Type: application/json

{
    "title":"Video 01",
    "description": "Esse é o meu primeiro video!",
    "duration": 180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/61125a2c-485c-4045-a5a9-da59a33d3253
Content-Type: application/json

{
    "title":"Video 06",
    "description": "Test",
    "duration": 150
}

###

DELETE  http://localhost:3333/videos/ffcbbed5-11d5-4137-8a13-0426e0c71a41
###