POST http://localhost:3333/videos
Content-Type: application/json

{
    "title":"Video 01",
    "description": "Esse é o meu primeiro video!",
    "duration": 180
}

###

GET http://localhost:3333/videos?search=Test

###

PUT http://localhost:3333/videos/2a479166-a48a-485d-96ac-2d4014124665
Content-Type: application/json

{
    "title":"Test",
    "description": "Loremin",
    "duration": 150
}

###

DELETE  http://localhost:3333/videos/ffcbbed5-11d5-4137-8a13-0426e0c71a41
###